#!/usr/bin/env python

from __future__ import print_function

import base64
import copy
import os
import re
import struct
import subprocess
import sys
import threading
import unittest

try:
    from http.server import BaseHTTPRequestHandler, HTTPServer
    from urllib.parse import parse_qs, urlsplit
except ImportError:
    from BaseHTTPServer import BaseHTTPRequestHandler, HTTPServer
    from urlparse import parse_qs, urlsplit

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir))
SCRIPT = os.path.join(ROOT, "identYwaf.py")

if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

import identYwaf


class QuietStream(object):
    def write(self, value):
        pass

    def flush(self):
        pass


class DataTests(unittest.TestCase):
    def test_database_is_valid(self):
        errors, warnings, stats = identYwaf.validate_data(identYwaf.DATA_JSON)

        self.assertEqual(errors, [])
        self.assertEqual(stats["wafs"], 95)
        self.assertEqual(stats["payloads"], 45)
        self.assertEqual(stats["signatures"], 248)
        self.assertEqual(stats["unique_signatures"], 247)
        self.assertEqual(len(warnings), 1)

    def test_known_signature_collision_keeps_both_owners(self):
        collisions = [owners for owners in identYwaf.SIGNATURES.values() if len(owners) > 1]
        self.assertEqual(len(collisions), 1)
        self.assertEqual(set(collisions[0]), set(("cdnns", "janusec")))

    def test_payload_changes_are_detected(self):
        data = copy.deepcopy(identYwaf.DATA_JSON)
        data["payloads"][0] += "changed"
        errors, _, _ = identYwaf.validate_data(data)
        self.assertTrue(any("payloads_hash mismatch" in error for error in errors))

    def test_all_recognition_regexes_compile(self):
        self.assertEqual(len(identYwaf.WAF_PATTERNS), 91)
        self.assertEqual(re.compile(identYwaf.WAF_RECOGNITION_REGEX).groups, 9)
        self.assertTrue(identYwaf.WAF_PATTERNS["aws"].search("Request blocked\nGenerated by cloudfront"))
        self.assertTrue(identYwaf.WAF_PATTERNS["sonicwall"].search("<title>Web Site Blocked</title>\nnsa_banner"))


class ArgumentTests(unittest.TestCase):
    def parse(self, arguments):
        original_argv = sys.argv
        original_stderr = sys.stderr
        try:
            sys.argv = [SCRIPT] + arguments
            sys.stderr = QuietStream()
            identYwaf.parse_args()
            return identYwaf.options
        finally:
            sys.argv = original_argv
            sys.stderr = original_stderr

    def test_options_can_follow_target(self):
        options = self.parse(["example.com", "--post"])
        self.assertEqual(options.url, "http://example.com")
        self.assertTrue(options.post)

    def test_missing_target_is_rejected(self):
        self.assertRaises(SystemExit, self.parse, ["--random-agent"])

    def test_non_http_scheme_is_rejected(self):
        self.assertRaises(SystemExit, self.parse, ["ftp://example.com"])


class ProxyTests(unittest.TestCase):
    def test_dead_proxy_list_is_tried_once_and_stops(self):
        class Options(object):
            timeout = 1

        calls = []
        original_options = identYwaf.options
        original_proxies = list(identYwaf.proxies)
        original_proxies_index = identYwaf.proxies_index
        original_urlopen = identYwaf.urlopen
        original_install = identYwaf._install_http_opener
        original_stdout = sys.stdout

        def fail(*args, **kwargs):
            calls.append(args[0])
            raise IOError("offline")

        def ignore_proxy(proxy=None):
            pass

        try:
            identYwaf.options = Options()
            identYwaf.proxies[:] = ["http://proxy-one", "http://proxy-two"]
            identYwaf.proxies_index = 0
            identYwaf._install_http_opener = ignore_proxy
            identYwaf.urlopen = fail
            sys.stdout = QuietStream()
            self.assertRaises(SystemExit, identYwaf.retrieve, "http://example.com")
            self.assertEqual(len(calls), 2)
        finally:
            identYwaf.options = original_options
            identYwaf.proxies[:] = original_proxies
            identYwaf.proxies_index = original_proxies_index
            identYwaf.urlopen = original_urlopen
            identYwaf._install_http_opener = original_install
            sys.stdout = original_stdout


class FingerprintHandler(BaseHTTPRequestHandler):
    blocked_by_payload = {}

    def _payload(self, value):
        values = parse_qs(value, keep_blank_values=True)
        return list(values.values())[0][0] if values else None

    def _respond(self, payload):
        blocked = payload is not None and not payload.isdigit() and (payload not in self.blocked_by_payload or self.blocked_by_payload[payload])
        self.send_response(403 if blocked else 200)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.end_headers()
        body = b"<html><title>Blocked</title>request denied</html>" if blocked else b"<html><title>Home</title>ok</html>"
        self.wfile.write(body)

    def do_GET(self):
        self._respond(self._payload(urlsplit(self.path).query))

    def do_POST(self):
        length = int(self.headers.get("Content-Length", 0))
        body = self.rfile.read(length)
        if not isinstance(body, str):
            body = body.decode("ascii")
        self._respond(self._payload(body))

    def log_message(self, *args):
        pass


class EndToEndTests(unittest.TestCase):
    @classmethod
    def use_signature(cls, signature):
        decoded = base64.b64decode(signature.split(':', 1)[1])
        parts = struct.unpack(">%dH" % len(identYwaf.PAYLOADS), decoded)
        FingerprintHandler.blocked_by_payload = dict((item.split("::", 1)[1], part & 1) for item, part in zip(identYwaf.PAYLOADS, parts))

    @classmethod
    def setUpClass(cls):
        cls.signature = identYwaf.DATA_JSON["wafs"]["360"]["signatures"][0]
        cls.use_signature(cls.signature)
        cls.server = HTTPServer(("127.0.0.1", 0), FingerprintHandler)
        cls.thread = threading.Thread(target=cls.server.serve_forever)
        cls.thread.daemon = True
        cls.thread.start()
        cls.url = "http://127.0.0.1:%d/" % cls.server.server_port

    @classmethod
    def tearDownClass(cls):
        cls.server.shutdown()
        cls.thread.join()
        cls.server.server_close()

    def scan(self, *extra):
        command = [sys.executable, "-B", SCRIPT, "--code=403", self.url] + list(extra)
        process = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, cwd=ROOT)
        output = process.communicate()[0]
        if not isinstance(output, type(u"")):
            output = output.decode("utf8", "replace")
        self.assertEqual(process.returncode, 0, output)
        return output

    def run_scan(self, *extra):
        self.use_signature(self.signature)
        output = self.scan(*extra)
        self.assertIn("signature: '%s'" % self.signature, output)
        self.assertIn("blind match: '360' (100%)", output)

    def test_get_fingerprint(self):
        self.run_scan()

    def test_post_fingerprint(self):
        self.run_scan("--post")

    def test_shared_fingerprint_reports_both_candidates(self):
        signature = list(identYwaf.DATA_JSON["signature_collisions"])[0]
        self.use_signature(signature)
        output = self.scan()
        self.assertIn("'CdnNsWAF (CdnNs/WdidcNet)' (100%)", output)
        self.assertIn("'Janusec Application Gateway (Janusec)' (100%)", output)


if __name__ == "__main__":
    unittest.main()
